"""Added payment mothd to Registered Student

Revision ID: a2d49c985556
Revises: 
Create Date: 2025-02-07 10:53:07.929198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d49c985556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registeredstudent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registeredstudent', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
